### PR TITLE
Adding epoch_prop and epoch_prop_pos

### PR DESCRIPTION
**Pull request by msdemlei**
These functions are implemented at the GAIA and GAVO DC TAP services.

### CODE REVIEW

**Review by mbtaylor — DISMISSED** [review]
Looks OK (though by all means wait for @jontxu's review).  More whitespace changes I see.
One suggestion: I believe it is the case that only the difference of ref_epoch and out_epoch affects the result, not their absolute values.  Assuming that's the case, I suggest adding a note clarifying this fact to aid understanding of what's going on.

**Comment by msdemlei** [comment]
On Fri, Jun 16, 2023 at 02:32:15AM -0700, Mark Taylor wrote:
> @mbtaylor approved this pull request.
>
> Looks OK (though by all means wait for @jontxu's review).  More
> whitespace changes I see.

Oh right.  Forgot about those.  However, since it's below 10 lines or
so, I'd ask for clemency.

> One suggestion: I believe it is the case that only the difference
> of ref_epoch and out_epoch affects the result, not their absolute
> values.  Assuming that's the case, I suggest adding a note
> clarifying this fact to aid understanding of what's going on.

Added some language to that effect in commit
45a5137d1b398479d2728af94a5aad38c8384853.  Is that what you had in
mind?

**Review by mbtaylor — CHANGES_REQUESTED** [review]
Yes good thank you.
(Interestingly I note that this commit deletes some trailing whitepace added in new text from one of the earlier commits that threw out trailing whitespace in pre-existing text.)

**Review by mbtaylor — APPROVED** [review]

**Comment by jontxu** [comment]
It also looks fine by me.

**Pull request merged**
