### PR TITLE
Revert "Remove appendix with third party UDFs"

### PR DESCRIPTION
**Pull request by jontxu**
Reverts ivoa-std/udf-catalogue#6

### CODE REVIEW

**Comment by jontxu** [comment]
Whoops, I merged #5 and #6 at the same time with the latter as seen in 8eb7d1175a6c1c32a7366aa77a4626696859478c. I hope that is fine... perhaps reverting it and making it correctly would be better. Sorry!

**Comment by gmantele** [comment]
This PullRequest seems to conflict with the current version of the document while being a month old.
What is the expected status of it? Should it be dropped or merged at some point?

**Comment by jontxu** [comment]
It was a mistake on my part, I forgot to close it.

**Comment by gmantele** [comment]
No worry. It was not really a mistake. I just wanted to help cleaning the PullRequest list.
Thank you for this update.

**Pull request closed without merging**
