### PR TITLE
Added celestial conversion functions

### PR DESCRIPTION
**Pull request by tcivera**
Added celestial conversion functions: ivo_hms_to_degrees and ivo_dms_to_degrees. Solved in README an errata in IVOATexDoc link. Deleted aaps command to solve bug with make.

### CODE REVIEW

**Review by mbtaylor — CHANGES_REQUESTED** [review]
Looks OK, though I don't know what is common practice if any in existing services, so I don't comment on the form and naming of the functions.

But I would suggest one change: make it clear that a `+` or `-` sign is permitted in `ivo_dms_to_degrees`, and maybe include a sexagesimal string with a sign in the examples.  It might also be a good idea to draw attention to the fact that it's easy to write implementations that get negative-zero parsing wrong - perhaps include an example like  "`-00:15:00`" (=-0.25deg).

Should an optional sign be permitted for `ivo_hms_to_degrees` as well?  Not sure.

**Comment by tcivera** [comment]
Indicated that ivo_dms_to_degrees allows + or - sign and examples of this added.
I am not sure either that it should be also permitted for ivo_hms_to_degrees function, so I have not included on it.

**Comment by msdemlei** [comment]
On Fri, Jan 26, 2024 at 03:52:21AM -0800, Tamara Civera wrote:
> I am not sure either that it should be also permitted for
> ivo_hms_to_degrees function, so I have not included on it.

Interesting question.  Over at DALI we've discussed the legal ranges
of coordinates in their geometries, and I have argued that "small
negative" RAs need to be possible to allow meridian-stretching
polygons without brain knots.

But here... I don't know.  I think the basic use case is parsing
legacy coordinate specifications in strings in uploaded data.  How
likely is it that they have negative RAs?  In particular, I *really*
hope nobody will ever express spherical polygons in Babylonian
notation.

So, I'd say no sign on RAs.

**Review by mbtaylor — APPROVED** [review]
Looks good, thanks for the changes.

**Comment by mbtaylor** [comment]
@msdemlei it looks like you just closed this PR without comment, which I'm guessing you didn't mean to do.  Presumably related to the fact that this is a PR against the `ivoa-std:add-transform-and-co` branch which you merged and deleted.  Do something to reinstate this one?  And merge if you agree.

**Comment by msdemlei** [comment]
On Thu, Feb 01, 2024 at 01:06:39AM -0800, Mark Taylor wrote:
> @msdemlei it looks like you just closed this PR without comment,
> which I'm guessing you didn't mean to do.  Presumably related to

No, I didn't.  Oh dang.

> the fact that this is a PR against the
> `ivoa-std:add-transform-and-co` branch which you merged and
> deleted.  Do something to reinstate this one?  And merge if you
> agree.

Well, live and learn.  That behaviour is sort of logical on the side
of github, but it's certainly surprising.

Let me figure out a way to recover.

As to merging, my current plan is to wait for a second
implementation in a (probably silly) attempt to keep the document
history neat.  I'm hoping for VizieR but will do it myself if
necessary (at least this is the right direction: *from* Babylonian
*to* sensible:-).

**Comment by tcivera** [comment]
ivo_dms_to_degrees and ivo_hms_to_degrees implemented at CEFCA/OAJ TAP service: https://archive.cefca.es/catalogues/vo/tap/jplus-dr3

**Comment by tcivera** [comment]
I propose that 'ivo_dms_to_degrees' and ' ivo_hms_to_degrees' functions return NULL value when they can not parse the input instead of giving an error to avoid killing large operations just for one row.

**Review by mbtaylor — APPROVED** [review]
I agree with the intent.  It's how I would have interpreted it anyway, but it doesn't hurt to make the behaviour explicit.

**Comment by jontxu** [comment]
Hi, I was able to implement both functions at the ARI Gaia TAP service. Nevertheless, my only question before deploying is whether is worth it to normalise the respective angles or should it be left to the user whenever it happens.

**Pull request merged**
